name: vision
channels:
- anaconda-fusion
- defaults
dependencies:
- freetype=2.5.5=2
- icu=54.1=0
- libpng=1.6.27=0
- openssl=1.0.2k=2
- pip=9.0.1=py35_1
- pyqt=5.6.0=py35_2
- python=3.5.1=5
- qt=5.6.2=0
- readline=6.2=2
- setuptools=27.2.0=py35_0
- sip=4.18=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- zlib=1.2.8=3
