name: road_sign_detection
channels:
- anaconda-fusion
- defaults
dependencies:
- mkl=2017.0.1=0
- numpy=1.13.0=py27_0
- openssl=1.0.2l=0
- pip=9.0.1=py27_0
- python=2.7.13=0
- readline=6.2=2
- scikit-learn=0.18.1=np113py27_0
- scipy=0.19.0=np113py27_0
- setuptools=27.2.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - click==6.7
  - cycler==0.10.0
  - decorator==4.0.11
  - flask==0.12.2
  - functools32==3.2.3.post2
  - itsdangerous==0.24
  - jinja2==2.9.6
  - markupsafe==1.0
  - matplotlib==2.0.2
  - networkx==1.11
  - olefile==0.44
  - opencv-python==3.2.0.7
  - pillow==4.1.1
  - pyparsing==2.2.0
  - python-dateutil==2.6.0
  - pytz==2017.2
  - pywavelets==0.5.2
  - scikit-image==0.13.0
  - six==1.10.0
  - subprocess32==3.2.7
  - werkzeug==0.12.2

