name: TrafficSignRecognition
channels:
- anaconda-fusion
- defaults
dependencies:
- pip=9.0.1=py27_1
- python=2.7.13=0
- wheel=0.29.0=py27_0
- pip:
  - flask==0.12.2
  - matplotlib==2.0.2
  - numpy==1.13.0
  - scikit-image==0.13.0
  - scipy==0.19.0


